### ISSUE TITLE
Generate Enap_blank.itp

### ISSUE THREAD

**Issue by shafayetrahat** [rmera/bartender#2]
When using bartender we need a blank.itp( ex. Enap_blank.itp) file for the input of the "write_bartender_inp.py" file. I am seeing a lot of values set in the blank.itp but doesn't know where they came from. There is no proper instruction on how to generate Enap_blank.itp file efficiently. Also, there is no proper instruction in the martini repository on this topic. Could anyone please explain to me how to generate the Enap_blank.itp? If we need to do it by hand then can anyone share the tricks to set the values in the blank.itp file?

**Comment by rmera** [comment]
Bartender generates the bonded parameters for a system, and it does so starting from an atomistic structure and an input file that contains the atomistic->CG mapping (i.e. which atoms correspond to which CG beads), and also the bonded parameters you want to generate.

write_bartender_inp.py is only an utility that, given a Gromacs itp with the description of the CG system and with the bonded parameters you want, and a Gromacs ndx with the atomistic->CG mapping, can generate the Bartender input for you. The itp file is just the file you will need anyway to run your simulations in Gromacs once Bartender obtains bonded parameters for you.

Generating the aforementioned itp and ndx are not really a Bartender use issue, but a Gromacs use issue. I recommend you check out the Gromacs documentation for that.
